### PR TITLE
enable the annotateit.org bookmarklet

### PR DESCRIPTION
**Pull request by ingoradatz**
The API path /annotations stores and removes annotations along the methods POST, PUT and DELETE. A customised bookmarklet (see README.md) can be used to create and update annotations on every website visited. The README.md explains how to configure the CouchDB to support the bookmarklet CORS requests.

Have fun!

### CODE REVIEW

**Comment by vmx** [comment]
Thanks for the pull request. When I try the bookmarklet, it tries to access the `/search` endpoint (which doesn't exist). It then fails with "Sorry we could not connect to the annotations store". Though you can store annotations, but they can't retrieved as the `/search` endpoint is used for it.

Is there a way to change the behaviour of the bookmarklet to not use the `/search` endpoint (as it is done in the demo.html)?

**Comment by vmx** [comment]
@tilgovi just pointed out that `/search` could probably be implemented as list function. That sounds like a good solution to the problem.

**Comment by ingoradatz** [comment]
@vmx @tilgovi

Deleting documents seems to be impossible without changing code of the bookmarklet. We would need the `rev` query parameter but it only sends the `_rev` property as data. Any trick to rewrite that? The rewrite handler has no access to payload and cannot change the HTTP method.

**Comment by tilgovi** [comment]
I think Couch is okay with the _rev being inline, only in the document but not in the query string.

**Comment by ingoradatz** [comment]
@tilgovi docs and tests saying no: http://wiki.apache.org/couchdb/HTTP_Document_API#DELETE

**Comment by ingoradatz** [comment]
@vmx @tilgovi 

TIL: update handlers are also accessible via the DELETE method - nice

**Comment by ingoradatz** [comment]
good old stuff but ... bye 👋

**Pull request closed without merging**
